# Generated by Django 2.1.7 on 2019-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicTacToe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField(max_length=100, verbose_name='board details')),
                ('result', models.CharField(choices=[('Player 1 Win', 'Player 1 Win'), ('Player 2 Win', 'Player 2 Win'), ('DRAW', 'DRAW'), ('PROGRESS', 'PROGRESS')], default='PROGRESS', max_length=100, verbose_name='result field')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
