# Generated by Django 2.1.7 on 2019-04-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_auto_20190423_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe',
            name='player_1_choice',
            field=models.CharField(default=-1, max_length=10, verbose_name='player one choice'),
        ),
        migrations.AddField(
            model_name='tictactoe',
            name='player_2_choice',
            field=models.CharField(default=1, max_length=10, verbose_name='player two choice'),
        ),
    ]
